// scripts/seedOsm.js
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });
const { createClient } = require('@supabase/supabase-js');
const axios = require('axios');

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

// Overpass QL Query: Finding hotels with eco/sustainable tags in Singapore
// Optimized Overpass QL Query
const OVERPASS_QUERY = `
  [out:json][timeout:90];
  // Target the Federal Territory of Kuala Lumpur
  area["name"="Kuala Lumpur"]["admin_level"="4"]->.searchArea;
  (
    node["tourism"="hotel"](area.searchArea);
  );
  // Still limiting to 20 to ensure a fast, successful response
  out center 20;
`;

async function seedDatabase() {
    console.log('Fetching data from OpenStreetMap...');

    try {
        // 1. Fetch Data from Overpass API
        // Add a 100-second timeout (100000ms) to Axios
        const response = await axios.post(
            'https://overpass-api.de/api/interpreter',
            `data=${encodeURIComponent(OVERPASS_QUERY)}`,
            { timeout: 100000 }
        );
        const elements = response.data.elements;

        if (!elements || elements.length === 0) {
            console.log('No locations found matching the query.');
            return;
        }

        console.log(`Found ${elements.length} locations. Formatting data...`);

        // 2. Format Data to match your Supabase schema
        const formattedLocations = elements.map((el) => {
            const tags = el.tags || {};

            // Determine coordinates depending on if it's a node (point) or way (area)
            const lat = el.lat || el.center?.lat;
            const long = el.lon || el.center?.lon;

            // Extract eco-certifications (you can expand this logic)
            const certs = [];
            if (tags.eco) certs.push(`eco: ${tags.eco}`);
            if (tags.sustainable) certs.push(`sustainable: ${tags.sustainable}`);

            return {
                // id: will be auto-generated by Supabase if your column is set to gen_random_uuid()
                name: tags['name:en'] || tags.name || 'Unnamed Eco Hotel',
                category: 'Accommodation',
                city: 'Kuala Lumpur',
                lat: lat,
                long: long,
                eco_certs: certs, // maps to jsonb
                ex_booking_url: tags.website || null
            };
        }).filter(loc => loc.lat && loc.long); // Ensure we have valid coordinates

        // 3. Insert into Supabase
        console.log('Inserting into Supabase locations table...');
        const { data, error } = await supabase
            .from('locations')
            .insert(formattedLocations)
            .select();

        if (error) {
            console.error('Error inserting data:', error);
        } else {
            console.log(`Successfully inserted ${data.length} records!`);
        }

    } catch (error) {
        console.error('An error occurred during seeding:', error.message);
    }
}

seedDatabase();